# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar: "true"
resume_name: "Steve Forkin"
resume_title: "Senior Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email: "steve@netflakes.co"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone: "+61 474 809 224"
resume_contact_address: "1/42 Collingwood St, Coffs Harbour, NSW 2450"

resume_header_contact_info: "1/42 Collingwood St, Coffs Harbour, NSW 2450 • +61 474 809 224 • steve@netflakes.co"
display_header_contact_info: "false"

resume_header_intro:
  "<p>I have a background in a range of software development and team
  leader roles and have worked with a range of industry clients to
  deliver large scale projects. Networking protocols, how these
  are implemented in operating systems and how they impact the
  software development life-cycle is really important and part of
  my ongoing skill set. I am very passionate about Test Driven
  Development</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work: "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience: true
resume_section_education: true
#resume_section_projects: true
#resume_section_skills: true
#resume_section_recognition: true
resume_section_links: true
#resume_section_associations: true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url: "https://github.com/jglovier/resume-template"
  # resume_twitter_url: "http://twitter.com/jglovier"
  # resume_dribbble_url: "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url: "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url: "http://netflakes.github.io"
resume_print_social_links: true

# Design settings
resume_theme: default
# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
